name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # Lint:
  # Lint任务
  UnitTest:
    # 单元测试任务
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: pnpm run test:run
      - name: "Send mail"
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} completed successfully!
          to: 18618166564@163.com
          from: GitHub Actions
